### ISSUE TITLE
Add option to get results as JSON

### ISSUE THREAD

**Issue by cowchimp** [WPO-Foundation/visualmetrics#10]
Hi.

WDYT about adding an option (via command line parameter) to get back the results as JSON?
Could be useful to build tools around visualmetrics.

Thanks.

**Comment by pmeenan** [comment]
sgtm and shouldn't be much effort.

**Comment by cowchimp** [comment]
I'd send a PR but I don't speak python :snake: :grimacing:

**Comment by pmeenan** [comment]
np, I'll take a look but I'm into something else right now so it may take a little bit.

**Comment by cowchimp** [comment]
Fixed by #11 & #12.

`VisualProgress` is still a string but don't see a reason to leave this issue open just because of that.
