### ISSUE TITLE
[Questions] Using --multiple

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/visualmetrics#29]
Hi Pat, 
I have two questions about using --multiple to split a video. I can do PR but wanted to check first what's the correct behaviour:

1. Using perceptual has a check that you really provide a video: https://github.com/WPO-Foundation/visualmetrics/blob/master/visualmetrics.py#L1734-L1738 - but if you run --multiple and split the video into multiple runs, and then use Visual Metrics with the screenshots, that should work to get perceptual Speed Index right, so I can remove that check or how should it be used?

2. Using --multiple always exit with 1 because that ok is always set to false in https://github.com/WPO-Foundation/visualmetrics/blob/master/visualmetrics.py#L1795 and then we exit on that status in https://github.com/WPO-Foundation/visualmetrics/blob/master/visualmetrics.py#L1863-L1866. I can fix that but not sure how you wanna handle it? Exit on 0 helps me find when something is really wrong.

Best
Peter

**Comment by pmeenan** [comment]
Honestly, I have no idea.  --multiple was added for a temporary need where we needed to split a bunch of videos that were captured as a sequence.  Feel free to make whatever changes you need to get it working.

**Comment by soulgalore** [comment]
Had problems sometimes that the video wasn't split correctly so I'm going with the approach of recording one video per URL instead of splitting the video, so let us leave it as it is.
