### ISSUE TITLE
Python 2 is going out of support

### ISSUE THREAD

**Issue by ntova** [WPO-Foundation/visualmetrics#32]
Would a pull request to port this script to python3 be accepted?

It may be possible to make this script work in python2 and python3 by using the right `__future__` imports.

[Python 2 is going out of support in April 2020](https://www.python.org/psf/press-release/pr20191220/).

**Comment by pmeenan** [comment]
Sorry, the porting work was already done in the wptagent project, the updated script just wasn't copied over here.  I'll copy it over in a few minutes.
