### ISSUE TITLE
ImportError: No module named argparse

### ISSUE THREAD

**Issue by andreapernici** [WPO-Foundation/visualmetrics#9]
When I execute the test I get:

# python visualmetrics.py --check
Traceback (most recent call last):
  File "visualmetrics.py", line 971, in <module>
    main()
  File "visualmetrics.py", line 853, in main
    import argparse
ImportError: No module named argparse

**Comment by pmeenan** [comment]
What version of Python are you running?  There's a good chance that it needs to be 2.7

**Comment by andreapernici** [comment]
Ok. I think it's the problem.

I'd like to pull SpeedIndex metrics inside Google Analytics. Do you think there is a way to that using UserTimings? How can I run the visualmetrics during the user visit in background?

**Comment by pmeenan** [comment]
I think you're looking for the [RUM_SpeedIndex](https://github.com/WPO-Foundation/RUM-SpeedIndex) project instead which can run in a browser.  This one is for running at a command line and takes a video of a page load as input, neither of which you have during a user visit.

**Comment by andreapernici** [comment]
Great. So I only need to include it in the page?
Which are the contraints? I need to load it sync or async?

If I understand well I only need to include the file in the page and send the returned SpeedIndex value to a Google Analytics event.

Thanks.
